apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: skr-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lRUnpWMXFBaUJja0tFUG9hUTZrY2xSVEFOQmdrcWhraUc5dzBCQVFzRkFEQWQKTVJzd0dRWURWUVFERXhKM1lYUmphR1Z5TFhkbFltaHZiMnN0WTJFd0lCY05Nakl3T0RJMk1USXpOekU0V2hnUApNakV5TWpBNE1ESXhNak0zTVRoYU1CMHhHekFaQmdOVkJBTVRFbmRoZEdOb1pYSXRkMlZpYUc5dmF5MWpZVENDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTExONmFkUlgraDZxWEdhWG1Gb3IzOG0KeXhSVE9nSGhiVFgwN2dMNmRVMldjdFY5Yk5Na3VMY1dOcHNvWWl2ekhqT3N2Y0hhY0lOcnczQWg5bm5QU2NBdwpVbW5SMFo0L0VQNGNoZ3ovT2wyOHFPWTliNE0xNWQ3eXg1dnprL1F0VUlGRzBFNFppVXVzbUNSR05mb1FUZU5DCjRVNTVSNSsyY0FLalVScm1lb0FJYTNFajZwK2ZURlpQaHJURGVtY2lLK0VqOFNGVWhrRHBJYUhFU0J0cEV6SmEKRTlUTktxUmVsaVhXYjhPbGk2STVrSEFMenY0S2FuY1N3WngyaHJhK1ZXbnZoSkttTTNvZ3U1REVDOWlWd0NBVgpka0lycGlGUzJpa1JVSWNsU2pVWUlONnQ1RjhCNGJEakROQ0tUNU0rV2NnTzZaS0ZOakxmZkk3dXQvM2tXcWtDCkF3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3IKQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlR3RUVZWm5aZ1BzcWd5eExzUwpEWE1nNjRmNndEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYS3ZzQzE0Nk9OMDhtZUlkQVVFRnp2amRNZFhjCmJwbVdncEpROWtpMkJYU1ZSNHFNeGNwWUpJbXR6cW1mTEY1ZWM5a3NMSUgyd0syMUJCM2ZicVRZMWhiekFRbVYKRDBNdFZxcE01eHVGbFNIcTk5S1hOeHkxTGlGRWJ3TS9lWFhxWnBhQWJJMmRDUkRXYzVnLzFXbVdnM3JyYXdVZQp3RHhLM3BCR1JsVXJIU1BJaDlWQjNoaUxjeVZOaWxDVTg0dEpmK09GbzRRUVJ2OWNRMkZtVG1HWmpuZ3BreTFjCm9udlk0VEp4eGhUU1JwSjlac0FmakJSWW1aanphaWJLS3p5T09EaWdjdXhvdjNacFpZbUtBbDM0a0pMenFyeFYKUXZ0M0lyMm1TV1Q3VEs0TXY1c2FRaW1hekl5enliamNyQm9pQXRxZDMxK0t4ekM0TmhCWTAzMERtdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: skr-webhook-svc
      namespace: kyma-system
      path: /kyma/validate
  failurePolicy: Fail
  name: kyma.webhook.kyma-project.io
  objectSelector:
    matchLabels:
      kyma-label: kyma-label-value
  rules:
  - apiGroups:
    - operator.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - '*'
    resources:
    - kymas
  sideEffects: NoneOnDryRun
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lRUnpWMXFBaUJja0tFUG9hUTZrY2xSVEFOQmdrcWhraUc5dzBCQVFzRkFEQWQKTVJzd0dRWURWUVFERXhKM1lYUmphR1Z5TFhkbFltaHZiMnN0WTJFd0lCY05Nakl3T0RJMk1USXpOekU0V2hnUApNakV5TWpBNE1ESXhNak0zTVRoYU1CMHhHekFaQmdOVkJBTVRFbmRoZEdOb1pYSXRkMlZpYUc5dmF5MWpZVENDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTExONmFkUlgraDZxWEdhWG1Gb3IzOG0KeXhSVE9nSGhiVFgwN2dMNmRVMldjdFY5Yk5Na3VMY1dOcHNvWWl2ekhqT3N2Y0hhY0lOcnczQWg5bm5QU2NBdwpVbW5SMFo0L0VQNGNoZ3ovT2wyOHFPWTliNE0xNWQ3eXg1dnprL1F0VUlGRzBFNFppVXVzbUNSR05mb1FUZU5DCjRVNTVSNSsyY0FLalVScm1lb0FJYTNFajZwK2ZURlpQaHJURGVtY2lLK0VqOFNGVWhrRHBJYUhFU0J0cEV6SmEKRTlUTktxUmVsaVhXYjhPbGk2STVrSEFMenY0S2FuY1N3WngyaHJhK1ZXbnZoSkttTTNvZ3U1REVDOWlWd0NBVgpka0lycGlGUzJpa1JVSWNsU2pVWUlONnQ1RjhCNGJEakROQ0tUNU0rV2NnTzZaS0ZOakxmZkk3dXQvM2tXcWtDCkF3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3IKQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlR3RUVZWm5aZ1BzcWd5eExzUwpEWE1nNjRmNndEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYS3ZzQzE0Nk9OMDhtZUlkQVVFRnp2amRNZFhjCmJwbVdncEpROWtpMkJYU1ZSNHFNeGNwWUpJbXR6cW1mTEY1ZWM5a3NMSUgyd0syMUJCM2ZicVRZMWhiekFRbVYKRDBNdFZxcE01eHVGbFNIcTk5S1hOeHkxTGlGRWJ3TS9lWFhxWnBhQWJJMmRDUkRXYzVnLzFXbVdnM3JyYXdVZQp3RHhLM3BCR1JsVXJIU1BJaDlWQjNoaUxjeVZOaWxDVTg0dEpmK09GbzRRUVJ2OWNRMkZtVG1HWmpuZ3BreTFjCm9udlk0VEp4eGhUU1JwSjlac0FmakJSWW1aanphaWJLS3p5T09EaWdjdXhvdjNacFpZbUtBbDM0a0pMenFyeFYKUXZ0M0lyMm1TV1Q3VEs0TXY1c2FRaW1hekl5enliamNyQm9pQXRxZDMxK0t4ekM0TmhCWTAzMERtdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: skr-webhook-svc
      namespace: kyma-system
      path: /compass/validate
  failurePolicy: Fail
  name: compass.webhook.kyma-project.io
  objectSelector: {}
  rules:
  - apiGroups:
    - component.kyma-project.io
    apiVersions:
    - v1alpha1
    operations:
    - '*'
    resources:
    - compasses
  sideEffects: NoneOnDryRun
  timeoutSeconds: 30
